name: TestWorkflow
on: push
jobs:
  Test-Job:
    name: TestingWorkflowJob1
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job was triggered by a${{ github.event_name }} event."

  Test-Job2:
    name: TestingWorkflowJob2
    runs-on: ubuntu-latest
    needs: Test-Job
    steps:
        - run: echo "This is my second job"